version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: limite
      POSTGRES_PASSWORD: limite
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /var/home/tatiane/volumesPodman/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tatianenmlua@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: always